// <auto-generated />
using AngularSQLite.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace AngularSQLite.Migrations
{
    [DbContext(typeof(ShitContext))]
    partial class ShitContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("AngularSQLite.Models.Shit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Size");

                    b.Property<string>("Smell");

                    b.HasKey("ID");

                    b.ToTable("Shit");
                });
#pragma warning restore 612, 618
        }
    }
}
